name: Bot Webhook Responder

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Проверка каждые 15 минут

permissions:
  contents: write

jobs:
  check_requests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install
      run: |
        pip install aiogram aiohttp

    - name: Run bot responder
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python responder.py