name: Send Message

on:
  issues:
    types: [opened]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Telegram
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            -d text="Новое сообщение из Issues: $TITLE%0A%0A$BODY"